#! /bin/sh

tabler_icons_path="/Users/yazeedalkhalaf/Downloads/tabler-icons-3.16.0"

rm -rf Sources/TablerIcons/Icons.xcassets
mkdir -p Sources/TablerIcons/Icons.xcassets

for icon in ${tabler_icons_path}/svg/outline/*.svg; do
    echo "copying ${icon}"
    icon_name=$(basename "$icon" .svg)
    icon_name="${icon_name}-outlined"
    mkdir -p "Sources/TablerIcons/Icons.xcassets/${icon_name}.imageset"
    cp "$icon" "Sources/TablerIcons/Icons.xcassets/${icon_name}.imageset/${icon_name}.svg"
    cat <<EOF > "Sources/TablerIcons/Icons.xcassets/${icon_name}.imageset/Contents.json"
{
  "images" : [
    {
      "filename" : "${icon_name}.svg",
      "idiom" : "universal"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
EOF
done
git add "Sources/TablerIcons/Icons.xcassets"

for icon in ${tabler_icons_path}/svg/filled/*.svg; do
    echo "copying ${icon}"
    icon_name=$(basename "$icon" .svg)
    icon_name="${icon_name}-filled"
    mkdir -p "Sources/TablerIcons/Icons.xcassets/${icon_name}.imageset"
    cp "$icon" "Sources/TablerIcons/Icons.xcassets/${icon_name}.imageset/${icon_name}.svg"
    cat <<EOF > "Sources/TablerIcons/Icons.xcassets/${icon_name}.imageset/Contents.json"
{
  "images" : [
    {
      "filename" : "${icon_name}.svg",
      "idiom" : "universal"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
EOF
done
git add "Sources/TablerIcons/Icons.xcassets"

generate_swift_file() {
  PLATFORM=$1
  IMPORT=$2
  IMAGE_TYPE=$3
  IMAGE_INIT=$4
  SWIFT_FILE="Sources/TablerIcons/TablerIcons+$PLATFORM.swift"
  echo "// This is autogenerated file" > $SWIFT_FILE
  echo "// DO NOT EDIT" >> $SWIFT_FILE
  echo "" >> $SWIFT_FILE
  echo "#if canImport($IMPORT)" >> $SWIFT_FILE
  echo "import $IMPORT" >> $SWIFT_FILE
  echo "" >> $SWIFT_FILE
  echo "extension TablerIcons {" >> $SWIFT_FILE
  for svg in Sources/TablerIcons/icons.xcassets/*.imageset; do
    echo "adding ${svg} to swift file"
    svg_name=$(basename "$svg" .imageset)
    camel_case_name=$(echo "$svg_name" | awk -F- '{for(i=2;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1' OFS= | sed 's/-//g')
    camel_case_name=$(echo "$camel_case_name" | sed 's/^\(.\)/\1/')
    if [ "$PLATFORM" = "iOS" ]; then
      echo "  public static let \`$camel_case_name\`: $IMAGE_TYPE = $IMAGE_INIT(named: \"$svg_name\", in: Bundle.module, compatibleWith: nil)!" >> $SWIFT_FILE
    else
      echo "  public static let \`$camel_case_name\`: $IMAGE_TYPE = $IMAGE_INIT(forResource: \"$svg_name\")!" >> $SWIFT_FILE
    fi
  done
  echo "}" >> $SWIFT_FILE
  echo "" >> $SWIFT_FILE
  echo "#endif" >> $SWIFT_FILE
  git add $SWIFT_FILE
}

generate_swift_file "iOS" "UIKit" "UIImage" "UIImage"
generate_swift_file "macOS" "AppKit" "NSImage" "Bundle.module.image"
